version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.7.3
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_CORS=true
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/readiness"]
      interval: 30s
      timeout: 10s
      retries: 3

  rag-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=medical_products
      - EMBEDDING_MODEL=BAAI/bge-large-ru-v1.5
      - LLM_MODEL=IlyaGusev/saiga_mistral_7b_qlora
      - USE_GPU=true
      - QUANTIZE_LLM=true
      - DEBUG=false
    depends_on:
      - qdrant
    networks:
      - rag-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  rag-network:
    driver: bridge

volumes:
  qdrant_data: