version: '3.8'

services:
  # Сервис Qdrant - векторная база данных
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - rag-network
    environment:
      - QDRANT_ALLOW_CORS=true
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/readiness"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Сервис RAG-системы
  rag-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - QDRANT_URL=http://qdrant:6333
      - COLLECTION_NAME=technical_documents
      - BATCH_SIZE=100
      - USE_GPU=true
      - LOAD_8BIT=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - rag-network
    depends_on:
      - qdrant
    restart: always

networks:
  rag-network:
    driver: bridge

volumes:
  qdrant_data:
